### ISSUE TITLE
Wrong slf4j version stated in repo description

### ISSUE THREAD

**Issue by andham** [jboss-logging/slf4j-jboss-logmanager#6]
The description of the repo states:
SLF4J (1.5.x) Backend for JBoss LogManager

"1.5.x" is wrong as v1.7.x of slf4j is used. I suggest removing the version here all together to prevent this to be missed the next time slf4j is upgraded.

**Comment by jamezp** [comment]
Thank you. Sorry I did not notice this issue until now. I've just removed the version.
